name: extractor-build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git unzip protobuf-compiler build-essential curl

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: arduino/setup-protoc@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: |
        export RUSTFLAGS="-C target-cpu=x86-64"
        cargo build --release --features "SOLANA,RABBITMQ_CLASSIC,SINGLE_PUBLISHER"

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} target/release/blockchain_etl_indexer --clobber
